name: "Install Python Dependencies and Run Tests"
description: "Installe les dépendances Python et exécute les tests"
author: "Hermann DJOKO"

inputs:
  python-version:
    description: "Version de Python à installer"
    required: true
  run-tests:
    description: "Exécuter les tests ou non"
    required: false
    default: "true"

outputs:
  test-status:
    description: "Le statut de l'exécution des tests"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}


