name: "Install Python Dependencies and Run Tests"
description: "Installe les dépendances Python et exécute les tests"
author: "Hermann DJOKO"

inputs:
  python-version:
    description: "Version de Python à installer"
    required: true
  run-tests:
    description: "Exécuter les tests ou non"
    required: false
    default: "true"

